const questions=[
{id:'age',title:'年齢を教えてください',options:[['18-22','18〜22歳'],['23-25','23〜25歳'],['26-29','26〜29歳'],['30-34','30〜34歳'],['35+','35歳以上']]},
{id:'job',title:'現在の仕事に最も近いものを教えてください',options:[['sales','営業会社・訪問販売'],['realestate','不動産営業'],['hrsales','人材・求人営業'],['reuse','買取・リユース営業'],['service','接客・販売・サービス'],['office','事務・バックオフィス'],['engineer','エンジニア・IT'],['marketing','マーケティング・広告'],['nurse','看護師・医療職'],['teacher','保育士・教育職'],['other','その他']]},
{id:'experience',title:'現在の仕事の経験年数を教えてください',options:[['lt1','1年未満'],['1-2','1年以上2年未満'],['2-3','2年以上3年未満'],['3-5','3年以上5年未満'],['5+','5年以上']]},
{id:'income',title:'現在の年収を教えてください',options:[['280','300万円未満'],['325','300万〜349万円'],['375','350万〜399万円'],['425','400万〜449万円'],['475','450万〜499万円'],['550','500万〜599万円'],['700','600万〜799万円'],['850','800万円以上']]},
{id:'area',title:'希望する勤務地を教えてください',options:[['tokyo','東京'],['osaka','大阪'],['fukuoka','福岡'],['nagoya','名古屋'],['any','上記のいずれでも可能'],['other','その他・未定']]},
{id:'achievement',title:'仕事での成果について最も近いものを教えてください',options:[['none','まだ明確な成果はない'],['stable','任された仕事を安定してこなしている'],['target','目標を達成したことがある'],['numbers','数字で説明できる成果がある'],['award','社内表彰・上位成績の経験がある'],['team','チーム全体の成果を改善したことがある']]},
{id:'management',title:'後輩指導やチーム管理の経験はありますか？',options:[['none','経験はない'],['support','新人・後輩をサポートした'],['training','新人教育を担当した'],['leader','少人数チームをまとめた'],['manager','複数名の目標・進捗を管理した']]},
{id:'direction',title:'転職するとしたら、どの方向に興味がありますか？',options:[['same','現在と同じ職種で年収を上げたい'],['near','経験を活かして別業界へ移りたい'],['nonSales','営業経験を活かして違う仕事へ移りたい'],['new','未経験の仕事に挑戦したい'],['engineer','エンジニア・IT職'],['marketing','マーケティング職'],['proposal','自分に合う仕事を知りたい']]},
{id:'priority',title:'転職先で最も重視する条件は何ですか？',options:[['income','年収'],['holiday','休日・残業時間'],['stability','会社の安定性'],['work','仕事内容'],['career','キャリアアップ'],['remote','リモートワーク'],['challenge','未経験から挑戦できること']]},
{id:'intent',title:'現在の転職に対する気持ちに最も近いものは？',options:[['active','現在、転職活動中'],['good','良い会社があれば転職したい'],['consult','転職した方がよいか相談したい'],['value','まずは市場価値を知りたい'],['notnow','今すぐ転職するつもりはない']]},
{id:'timing',title:'転職するとしたら、いつ頃を考えていますか？',options:[['1m','1か月以内'],['3m','3か月以内'],['6m','半年以内'],['1y','1年以内'],['good','良い会社があれば'],['listen','まずは話だけ聞きたい']]}
];
let index=0,answers={},lastResult=null;
const $=id=>document.getElementById(id);
function startDiagnosis(){index=0;answers={};show('quiz-screen');render();}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo({top:0,behavior:'smooth'});}
function render(){const q=questions[index];$('progress-label').textContent=`QUESTION ${index+1}`;$('progress-count').textContent=`${index+1} / ${questions.length}`;$('progress-fill').style.width=`${(index+1)/questions.length*100}%`;$('question-kicker').textContent='CAREER CHECK';$('question-title').textContent=q.title;$('question-help').textContent='最も近いものを1つ選んでください。';$('choices').innerHTML='';q.options.forEach(([v,l],i)=>{const b=document.createElement('button');b.type='button';b.className='choice'+(answers[q.id]===v?' selected':'');b.innerHTML=`<span class="choice-index">${i+1}</span><span>${l}</span>`;b.onclick=()=>{answers[q.id]=v;render()};$('choices').appendChild(b)});$('back-btn').disabled=index===0;$('back-btn').style.opacity=index===0?'.45':'1';$('next-btn').disabled=!answers[q.id];$('next-btn').textContent=index===questions.length-1?'結果を見る':'次へ';}
function goNext(){if(!answers[questions[index].id])return;if(index<questions.length-1){index++;render()}else result();}
function goBack(){if(index>0){index--;render()}}
function result(){const current=Number(answers.income||375);let addLow=20,addHigh=70,score=55;
if(['280','325'].includes(answers.income)){addLow=40;addHigh=110}if(answers.income==='375'){addLow=30;addHigh=90}if(answers.income==='425'){addLow=20;addHigh=80}if(answers.income==='475'){addLow=10;addHigh=70}if(answers.income==='550'){addLow=0;addHigh=60}if(answers.income==='700'){addLow=-20;addHigh=40}if(answers.income==='850'){addLow=-50;addHigh=10}
if(['target','numbers'].includes(answers.achievement)){addLow+=10;addHigh+=20;score+=10}if(['award','team'].includes(answers.achievement)){addLow+=20;addHigh+=40;score+=17}if(['training','leader','manager'].includes(answers.management)){addLow+=10;addHigh+=25;score+=10}if(['3-5','5+'].includes(answers.experience)){addLow+=10;addHigh+=20;score+=8}if(answers.area==='any'){addLow+=10;addHigh+=20;score+=8}if(['same','near'].includes(answers.direction)){score+=12}else if(['new','engineer','marketing'].includes(answers.direction)){addLow-=20;addHigh-=20;score-=8}if(['active','good'].includes(answers.intent))score+=10;if(['1m','3m','6m'].includes(answers.timing))score+=8;if(answers.priority==='remote')score-=8;if(answers.age==='35+')score-=8;
const low=Math.max(250,Math.round((current+addLow)/10)*10),high=Math.max(low+30,Math.round((current+addHigh)/10)*10);score=Math.max(25,Math.min(95,score));
let type='キャリア情報収集タイプ',summary='まずは現在の経験がどの企業や職種で評価されるかを知ることで、今後の選択肢を増やせるタイプです。';
if(['award','team'].includes(answers.achievement)&&['same','near'].includes(answers.direction)){type='即戦力ステップアップタイプ';summary='実績と経験を活かし、会社や業界を変えることで年収・待遇の改善を狙いやすいタイプです。'}else if(current<=425&&['target','numbers','award','team'].includes(answers.achievement)){type='隠れ高市場価値タイプ';summary='現在の実績が年収に十分反映されていない可能性があります。評価制度や業界を変えることで伸びやすいタイプです。'}else if(['new','engineer','marketing'].includes(answers.direction)){type='キャリアチェンジ成長タイプ';summary='転職直後の金額だけでなく、3〜5年後の市場価値を重視した職種選びが向いています。'}else if(['holiday','remote','work'].includes(answers.priority)){type='働き方見直しタイプ';summary='年収だけでなく、休日・残業・仕事内容を含めた条件改善を重視することで満足度が上がりやすいタイプです。'}
const diffLow=low-current,diffHigh=high-current;$('result-type').textContent=type;$('result-summary').textContent=summary;$('salary-range').textContent=`${low}万〜${high}万円`;$('salary-diff').textContent=diffHigh>0?`現在より年間${signed(diffLow)}万〜${signed(diffHigh)}万円の可能性`:'年収維持を前提に条件改善を検討';$('feasibility-label').textContent=`${score}%`;$('feasibility-fill').style.width='0';setTimeout(()=>$('feasibility-fill').style.width=`${score}%`,50);$('feasibility-note').textContent=score>=75?'経験と希望条件の整合性が高く、比較的求人を選びやすい状態です。':score>=55?'転職可能性は十分あります。実績整理と求人選定で結果が変わります。':'希望職種や条件を調整すると実現度を高められます。';
const strengths=[];if(['target','numbers','award','team'].includes(answers.achievement))strengths.push('成果を採用企業へ説明できる経験がある');if(['training','leader','manager'].includes(answers.management))strengths.push('教育・マネジメント経験がある');if(['3-5','5+'].includes(answers.experience))strengths.push('継続した実務経験がある');if(answers.area==='any')strengths.push('主要都市の求人を幅広く比較できる');while(strengths.length<3)strengths.push(['20代採用では成長可能性も評価されやすい','現在の経験を整理することで評価材料を増やせる','希望条件を明確にすると応募先を選びやすい'][strengths.length]);
list('strength-list',strengths);list('action-list',['売上・契約数・達成率などを数字で整理する','担当業務ではなく、自分の工夫と成果を説明できるようにする',answers.direction==='new'?'未経験職種では初年度年収と将来性を分けて比較する':'同職種・近い職種の求人から優先して比較する']);list('direction-list',[['sales','realestate','hrsales','reuse'].includes(answers.job)?'法人営業・人材・SaaSなど営業経験が活きる業界':'現在の対人経験や実務経験を活かせる職種','教育体制と評価基準が明確な成長企業','東京・大阪・福岡・名古屋の求人を比較する']);lastResult={type,low,high,score};show('result-screen');}
function list(id,a){$(id).innerHTML=a.map(x=>`<li>${x}</li>`).join('')}
function restartDiagnosis(){startDiagnosis()}
async function shareResult(){if(!lastResult)return;const t=`【20代キャリア年収診断】\n診断タイプ：${lastResult.type}\n推定転職年収：${lastResult.low}万〜${lastResult.high}万円\n転職実現度：${lastResult.score}%\n※簡易推定です。`;try{await navigator.clipboard.writeText(t)}catch(e){const x=document.createElement('textarea');x.value=t;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove()}$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function signed(n){return n>0?`＋${n}`:n<0?`−${Math.abs(n)}`:'±0'}